Isolate report consumer worker & handle a error
penguin-statistics/backend-next pull request #41
Opened 2022-04-09 10:03 UTC by innovationb1ue

Isolate the initiation of workers of NewReportService to a standalone function. Provide variability for the number of workers.

2022-04-09 10:51 UTC, FlandiaYingman requested changes
Hi,

I think the param `NumWorker` of function `startConsumerWorkers` should start with lowercase.

2022-04-09 11:02 UTC, innovationb1ue commented
> Hi,
> 
> I think the param `NumWorker` of function `startConsumerWorkers` should start with lowercase.

2022-04-09 11:55 UTC, GalvinGao commented
Hi! Thanks for your contribution! 

Unfortunately there is an ongoing refactor at #38. Before that PR gets merged, your contribution can't yet been merged. Sorry for the inconvenience ❤️

2022-04-20 06:28 UTC, GalvinGao approved these changes
lgtm

2022-04-20 06:28 UTC, merged