(WIP) feat: source grouped query
penguin-statistics/backend-next pull request #77
Opened 2022-05-14 11:49 UTC by AlvISsReimu

2022-05-14 16:18 UTC, FlandiaYingman approved these changes
lgtm at least for now

2022-05-15 06:00 UTC, GalvinGao requested changes

2022-05-15 06:00 UTC, GalvinGao commented on internal/service/trend.go
> +		currentBatch = append(currentBatch, allResults...)
Merge two `append`s

2022-05-15 07:35 UTC, GalvinGao approved these changes

2022-05-15 07:35 UTC, merged